const textArray = [
  {
    message: '<div class="message-inner-text"><h1>František Fekete<br>/ Fluid Identity Club</h1></div>'
  },
  {
    message: '<div class="message-inner-image-small"><img src="images/fluidentity-01.png"></div>'
  },
  {
    message: '<div class="message-inner-text">There is something terrifying just in&nbsp;front of you, but without real contours.</div>'
  },
  {
    message: '<div class="message-inner-text">Always the&nbsp;same ambivalence and anxiety, just in&nbsp;a&nbsp;different setting. I&nbsp;am growing tired of this flowing fluidity of time. It flows like honey from a&nbsp;spoon. I&nbsp;am afflicted by an inner darkness. Inner demons of visions of absence and disappearing. I&nbsp;am absent. I&nbsp;disappear.</div>'
  },
  {
    message: '<div class="message-inner-text">My insides are gripped by a&nbsp;sense of anxiety that cannot be defined. Stealthily creeping, it eludes labels.</div>'
  },
  {
    message: '<div class="message-inner-text">We live in&nbsp;the&nbsp;belief that there exists a&nbsp;relationship between us and the&nbsp;world. But I&nbsp;am no longer interested in&nbsp;what the&nbsp;world has to say. I&nbsp;would like to break free from my thoughts, to be an animal or a&nbsp;force of nature. To float in&nbsp;timelessness. Man is an animal that creates myths for itself. It is painful, for the&nbsp;myths exist already and we are obligated and predestined to find our relationships to them. But what if we don’t want to? I&nbsp;feel inclined towards life but at the&nbsp;same time feel a&nbsp;strong need to leave it behind. I&nbsp;would like to just watch it. I&nbsp;don’t want to leave this world. I&nbsp;just want to leave behind human perspective, the&nbsp;perspective of the&nbsp;constantly present imperative of bifurcating desires. How to become a&nbsp;stone? How to become the&nbsp;ocean?</div>'
  },
  {
    message: '<div class="message-inner-text">Fluid identity is created when a&nbsp;particular milieu is excessively closed off and self-affirming. But then it opens itself up to the&nbsp;world, and we come to a&nbsp;realization. We are someone else. We are someone else each and every time. But who? We can be anyone, our identity is fluid. Fluid Identity. Be your own Trickster.</div>'
  },
  {
    message: '<div class="message-inner-text"> I&nbsp;am absorbed within myself. The&nbsp;problem is this: The&nbsp;need to break free from the&nbsp;burden of the&nbsp;present moment, even though it is where I&nbsp;am trying to encompass more perspectives, more times. It is painful to immediately become one with the&nbsp;eternal. The&nbsp;present moment is narrow. It is a&nbsp;fissure in&nbsp;a&nbsp;rock wall through which just a&nbsp;few rays manage to pass, and yet they intensively blind the&nbsp;eye. Eternity cannot fit into this fissure, nor can the&nbsp;past and the&nbsp;future. It is like wanting to be everyone from one place, to mentally cover all the&nbsp;yearned-for spaces. And at the&nbsp;same time to understand everything in&nbsp;one moment. The&nbsp;yearning to combine one’s presence with an entire myriad of other presences. An imagination full of injurious assumptions that all go nowhere. An awakening sense of guilt. Do I&nbsp;blame the&nbsp;world for having wrapped itself around me?</div>'
  },
  {
    message: '<div class="message-inner-text">Except I&nbsp;don’t have the&nbsp;courage to run away. I&nbsp;just endure, like some insect in&nbsp;a&nbsp;greenhouse, caught by this world in&nbsp;which I&nbsp;love only those things that cannot be described by words and that are so difficult to share.</div>'
  },
  {
    message: '<div class="message-inner-text">The&nbsp;Self is in&nbsp;reality somewhere deep, the&nbsp;Self is not omnipresent.</div>'
  },
  {
    message: '<div class="message-inner-text">I (don’t) know where I&nbsp;am. I&nbsp;know who I&nbsp;can become (everyone), and who I&nbsp;cannot become (everyone). The&nbsp;tendency to become everyone, to become anyone and at the&nbsp;same time no-one. I&nbsp;felt so much energy that I&nbsp;felt like I&nbsp;had to divide it (myself) up. And that is the&nbsp;moment when I&nbsp;was split. That is the&nbsp;moment that brings me so much anxiety. I&nbsp;must not carry this energy within me, but next to me. I&nbsp;must be a&nbsp;reservoir of identity, a&nbsp;platform of fluid identity. Be your own battlefield. A platform collects information about itself in&nbsp;order to use it on itself, or against itself. It is a&nbsp;system that creates, destroys, and reshapes itself. To abandon what is human in&nbsp;the&nbsp;world.</div>'
  },
  {
    message: '<div class="message-inner-text">In order for man today to be whole, he must split himself apart. But he must not keep the&nbsp;split-off parts; he must hide them. One way of hiding things is to let them float freely.</div>'
  },
  {
    message: '<div class="message-inner-text">We all have (an) upside world(s) hidden within ourselves. These worlds can be laid bare in&nbsp;the&nbsp;light of day and the&nbsp;darkness of night. Let them fly about us, so that they will be available at any time but at the&nbsp;same time not destroy us with their presence, for the&nbsp;world cannot be seized with our inner hand, we can only observe its eternally changing facets. Some are mirrors and some are entrances. Entrances to further entrances. We cannot carry a&nbsp;labyrinth within us.</div>'
  },
  {
    message: '<div class="message-inner-text">I feel incomplete. Paradoxically, this incompleteness is rooted in&nbsp;the&nbsp;fact of “fluid identity” – i.e., in&nbsp;antithetical moods and entire mental paradigms. It is as if I&nbsp;had truly understood them and let them pass across me like nomads. They settle down, strike imperceptible roots, and are replaced by others. The&nbsp;great migration of the&nbsp;spirit. Constant, every day. In other words: not too little, but too much. My ideas overflow my body. One can rid oneself of ideas by storing them somewhere. And so I&nbsp;tried to project myself into other people, to turn them into horcruxes so that they can help me get rid of these truths (or hold on to them, since ambivalence suits me, offers a&nbsp;plurality of knowledge). And of course there is the&nbsp;emotional bond, which is painful. These people are me, after all, so when they go a&nbsp;part of me goes with them.</div>'
  },
  {
    message: '<div class="message-inner-text">To be a&nbsp;part of the&nbsp;world like a&nbsp;reservoir of worlds. Drops fall onto my face, which frowns from the&nbsp;blasts of cold air. I&nbsp;concentrate on each of them, I&nbsp;feel their wet touch; they are the&nbsp;embodiment of the&nbsp;present moment, they inconspicuously inspect my face, my mind, which would like to turn it into more than it is. Every morning starts a&nbsp;new world. One way of hiding things is by having them blend in&nbsp;with their surroundings. This morning, I&nbsp;am hiding among the&nbsp;drops. I&nbsp;become gray and cold, I&nbsp;become a&nbsp;part of the&nbsp;whole, and my eternity becomes the&nbsp;moment of the&nbsp;rain. I&nbsp;blend with the&nbsp;moment of events and objects, the&nbsp;web of relationships of matter and emotions, time and space. I&nbsp;become the&nbsp;moment, I&nbsp;become a&nbsp;part of the&nbsp;new world that lasts one Sunday morning.</div>'
  },
  {
    message: '<div class="message-inner-text">The&nbsp;roles have changed. It is no longer I&nbsp;as eternity and things as the&nbsp;moment, but vice versa – I&nbsp;am the&nbsp;moment and things are eternal. And their eternity is combined and mixed with their beauty, and I&nbsp;can savor it, rediscover the&nbsp;world every day, be someone else every day, because the&nbsp;world, too, is different every day.</div>'
  },
  {
    message: '<div class="message-inner-text">And then it was all consumed by the&nbsp;sweet present. My entire preceding life was suddenly insignificant. It led up to the&nbsp;one single moment of this night, which must never end. No pity, no hope, without past and future. No yearning – just a&nbsp;total and intense moment. Compression, dynamics. Suddenly, everything made sense and at the&nbsp;same time nothing mattered. My entire life could be interpreted in&nbsp;the&nbsp;flash of those seconds. The&nbsp;only direction was towards the&nbsp;present, but where it was going remained unknown. So deep was the&nbsp;inside of the&nbsp;body that there suddenly appeared a&nbsp;fissure, an entrance to or exit from my mind. The&nbsp;exit is located deep in&nbsp;the&nbsp;veins that pump the&nbsp;blood to the&nbsp;brain.</div>'
  },
  {
    message: '<div class="message-inner-text">Apathy, apathy, without movement. Phase zero. The&nbsp;phase of pain, but perhaps just a&nbsp;few days and there will again come the&nbsp;phase of the&nbsp;eternity of things and the&nbsp;moment of man. Time again flows from the&nbsp;spoon. If only life were to flow from the&nbsp;wrist. To shed one’s life like a&nbsp;snake shedding its skin. Apathy. The&nbsp;chilling sun inside of me.</div>'
  },
  {
    message: '<div class="message-inner-text">All ideas in&nbsp;all possible worlds are combined into one, into one tangle of inconceivable energy. It is like a&nbsp;Big Bang inside me, trying to get out through my mouth. It screams, but my throat won’t let it out. It goes inside, suffocated in&nbsp;my bowels. Spasms of the&nbsp;heart. The&nbsp;cold transforms my tears into pieces of ice, which fall onto the&nbsp;fur of polar bears. I&nbsp;would like for my insides to be turned into ice. Then it would be enough to come close to blazing warmth and all my memories and hopes would turn to water – water that the&nbsp;polar bears would carry out to the&nbsp;open ocean on their ice floes. Anywhere: to the&nbsp;north and to the&nbsp;south. To become one with a&nbsp;world without emotions. Yearning to become the&nbsp;ocean, while life is the&nbsp;skin that I&nbsp;wear. Man is emotional anarchy.</div>'
  },
  {
    message: '<div class="message-inner-text">It is snowing. It is snowing outside. The&nbsp;snow covers the&nbsp;pointy roofs of the&nbsp;churches. When angels fall from the&nbsp;sky, they will be impaled on their spires and rivers of their blood will flow through the&nbsp;streets and drip from the&nbsp;gutters. Do angels have blue blood? The&nbsp;androgynous beauty of angels. The&nbsp;mysterious skin of angels. My skin is covered in&nbsp;ordinary carnation, my body pulses red, and I&nbsp;am condemned to look up from below at the&nbsp;tops of the&nbsp;towers. How to become a&nbsp;planet? Anxiety fills emptiness. And so this anxiety is all the&nbsp;more anxious. It is cyclical in&nbsp;its own reflections. Narrow, constricting, angst, anxiousness. I&nbsp;just have to move to different parts. Parts – what a&nbsp;fitting word! Places that are set apart. It seems like I&nbsp;often end up in&nbsp;such parts. And I&nbsp;am forced to flee from them, to close myself off from them in&nbsp;order to find new ones. I&nbsp;don’t live my emotions, they live me. Emotional nomadism, emotional totality.</div>'
  },
  {
    message: '<div class="message-inner-text">It is incredible to realize how any intense experience of the&nbsp;present is condemned to become a&nbsp;mere memory, a&nbsp;reflection of an erstwhile pain or joy, but most commonly an unbearable combination of the&nbsp;two, gradually wilting and fading into barren nothingness. The&nbsp;present is a&nbsp;dry and barren desert.</div>'
  },
  {
    message: '<div class="message-inner-text">Our wolf stage helps us to fully accept ourselves. To accept ourselves, accept time, accept our place within it. To howl with the&nbsp;wolves in&nbsp;pure presence.</div>'
  },
  {
    message: '<div class="message-inner-text">The&nbsp;problem with fluid identity is that it is divided into constantly flowing lines, diverging and branching out, ignorant of their goals and without boundaries. The&nbsp;problem is in&nbsp;decentralization. Matter is an island whose center can be analyzed, and if the&nbsp;searched-for boundaries disappear in&nbsp;the&nbsp;haze of the&nbsp;morning fog or in&nbsp;fickle clouds, we can return to the&nbsp;starting point at the&nbsp;center and try again. Not only is thinking based on centralized matter, but it is anchored in&nbsp;one time, meaning that there is only one time, flowing from beginning to end. Everyone sets their own speed of flowing time within the&nbsp;context of crossing vector paths, thus mixing past, present, and future. The&nbsp;result is chaos. Or have we accepted the&nbsp;idea of unboundedness? Aimlessness requires an absence of hope and memories, for memories are the&nbsp;root of hope. The&nbsp;absence of hope and memories means to live in&nbsp;a&nbsp;latent present, in&nbsp;pure timelessness. Is this the&nbsp;state that some have called post-humanism? Are the&nbsp;decentralization of identity and the&nbsp;experience of timelessness the&nbsp;foundations of post-humanism?</div>'
  },
  {
    message: '<div class="message-inner-text">How to combine emotional and political emancipation? Colonized body, colonized mind. Emotions sprout through the&nbsp;body, the&nbsp;body flourishes through politics. It is all about emotions and politics.</div>'
  },
  {
    message: '<div class="message-inner-text">We must be born again every day as a&nbsp;new person whose character derives from how he thinks and what he has experienced that day. Only with the&nbsp;constant re-drawing of mental models can we create an untraceable structure incapable of commodifying and objectifying itself. Thus the&nbsp;yearning for timelessness. In timelessness, there is no structure and thus no sense of guilt. When there is no sense of guilt, there is no yearning for power, since that sense of guilt, that unknown and invisible hyper-object whose presence we constantly and strongly feel, is the&nbsp;organ that drives us. We fear it and serve it. People are a&nbsp;medium, people act and people think within the&nbsp;shackles of a&nbsp;constantly turning world that cannot be stopped. How to achieve this? The&nbsp;sense of guilt that is deeply ingrained in&nbsp;you is the&nbsp;reason that the&nbsp;world cannot be stopped. This sense was planned over the&nbsp;centuries by institutions that, claiming to be interested in&nbsp;collective emancipation, emancipated the&nbsp;non-human mechanism by which the&nbsp;dialectics of history have played out. The&nbsp;body is an archive.</div>'
  },
  {
    message: '<div class="message-inner-text">The&nbsp;insurmountability of (non)sense. Inner darkness. Perhaps it is not caused by the&nbsp;anxiety of what is inside, but by its openness and broadness, by the&nbsp;characteristics of the&nbsp;object. A field of cells, ones and zeros, cosmic and I&nbsp;don’t know what other distances – or rather proximities, for it would seem that everything important is hidden so close that it is impossible to see, so dulled are we by our yearning for distant parts. And these distant proximities remain unexplored, they are drowning in&nbsp;darkness but they can be seen, and this causes feelings of angst-filled conflict. A fear of distances, a&nbsp;fear of the&nbsp;unexplored whose latent presence is always so close. I&nbsp;am a&nbsp;partially illuminated web. We cannot rule out – in&nbsp;fact, it is highly likely – that never during my lifetime will it be illuminated as a&nbsp;whole. In fact, it is impossible. Because the&nbsp;individual human mind and body are not a&nbsp;whole, they are an indispensable part of a&nbsp;system, significant in&nbsp;their insignificance. And also because light travels; it is fluid, and so our interior is fluid as well. It will never be a&nbsp;whole because there is no truth. It does not exist in&nbsp;one place, but is mobile and nimble. Fluidity, the&nbsp;viscosity of truth. To indulge oneself in&nbsp;this fluid viscidity, in&nbsp;the&nbsp;fluctuation of energies. To renounce power, to renounce oneself in&nbsp;favor of a&nbsp;broader web of spiritual reality. To connect oneself to the&nbsp;world – which has already happened; it is naive to think otherwise, and we must accept and understand that fact. Technology and spirituality, an alternative passage of time, the&nbsp;past is the&nbsp;present is the&nbsp;future.</div>'
  },
  {
    message: '<div class="message-inner-text">In actuality, I&nbsp;am incomplete. I&nbsp;am absent, I&nbsp;am disappearing. The&nbsp;Self is absent, the&nbsp;Self is disappearing. I&nbsp;am full of holes. The&nbsp;Self is full of holes. A punctured identity needs to be filled with nomadic and stealthy movement. The&nbsp;incomplete (hierarchized) Self becomes emancipated (non-hierarchized) by flowing and transgressing itself. The&nbsp;identity of the&nbsp;Self is auto-frustration. I&nbsp;don’t have to feel incomplete, we are incomplete. Historical scars are a&nbsp;manifestation of absence within man. Man is an archive of scars. The&nbsp;scars open themselves to the&nbsp;world so that identity may escape. Scars created during the&nbsp;course of history can be used as a&nbsp;birthright, as a&nbsp;way out of the&nbsp;givenness of hierarchized identity and as a&nbsp;way into the&nbsp;space of fluid identities.</div>'
  },
  {
    message: '<div class="message-inner-text"> To escape power and possession through the&nbsp;scar of binarity. To escape on the&nbsp;fragments of beauty that have remained. Flowing as the&nbsp;only possibility, temporariness as the&nbsp;only condition.</div>'
  },
  {
    message: '<div class="message-inner-text">To create a&nbsp;fragile and transient archipelago condemned to be born and die (absence and loss as the&nbsp;only condition and only binarity).</div>'
  },
  {
    message: '<div class="message-inner-text">Fluid identity dances at the&nbsp;Fluid Identity Club. Translucent bodies reveal an archive of injuries. Scars are a&nbsp;way out of the&nbsp;immutability of Identities, which manifests the&nbsp;fact that man is condemned to power. Scars are portals of emancipation, a&nbsp;path of Nomadic disappearing. The&nbsp;Self transcends itself, it is an embodiment of divergence. The&nbsp;Emotional Anarchy behind the&nbsp;DJ table sets the&nbsp;rhythm of never-ending losing and finding, the&nbsp;only chance of escaping hierarchy. Identity molders and drowns, condemned to possess. Disappearing and absence are the&nbsp;only chance, temporariness the&nbsp;only condition. We are incomplete in&nbsp;our yearning for power; we must deviate. Identity is an archive of injuries. Imprisoning identity is a&nbsp;form of power, because identity comes into being through power relations. Letting identity float does not mean its death, but its birth in&nbsp;the&nbsp;form of constant inventing. It is our prerogative to abandon identity and become a&nbsp;medium, a&nbsp;fluid identity, a&nbsp;gravedigger of hierarchy. Identity must be split apart and become fluid, the&nbsp;gravedigger of hierarchy.</div>'
  }
];
